INSERT INTO C2010100 VALUES(0,'sctfxrczgcywxezs','130F0000','魔方密码','魔方密码','','',NOW,NOW)

INSERT INTO C2010200 VALUES(0,0,'0','sctfxrczgcywxezs','默认类别','默认类别','','',NOW,NOW)

INSERT INTO C2010200 VALUES(1,1,'sctfxrcwcecbyarb','sctfxrczgcywxezs','网络注册','网络注册','','',NOW,NOW)
INSERT INTO C2010200 VALUES(1,0,'qqqqqazdddvgtbdv','sctfxrcwcecbyarb','OpenID','OpenID','','',NOW,NOW)
INSERT INTO C2010200 VALUES(2,0,'qqqqqazdddgcaaqs','sctfxrcwcecbyarb','WebOS','WebOS','','',NOW,NOW)
INSERT INTO C2010200 VALUES(3,0,'qqqqqaavvfxtyrgf','sctfxrcwcecbyarb','网盘','网盘','','',NOW,NOW)
INSERT INTO C2010200 VALUES(4,0,'qqqqqaavwrebqxrs','sctfxrcwcecbyarb','下载','下载','download','',NOW,NOW)
INSERT INTO C2010200 VALUES(5,0,'qqqqqaarsawteyre','sctfxrcwcecbyarb','新闻','新闻','news','',NOW,NOW)
INSERT INTO C2010200 VALUES(6,0,'qqqqqaavwsdwtdvx','sctfxrcwcecbyarb','论坛','论坛','bbs','',NOW,NOW)
INSERT INTO C2010200 VALUES(7,0,'qqqqqaavwsdsarvg','sctfxrcwcecbyarb','博客','博客','blog','',NOW,NOW)
INSERT INTO C2010200 VALUES(8,0,'qqqqqaavwscvwqez','sctfxrcwcecbyarb','求职','求职','job','',NOW,NOW)
INSERT INTO C2010200 VALUES(9,0,'qqqqqaavwsdsedgg','sctfxrcwcecbyarb','交友','交友','','',NOW,NOW)
INSERT INTO C2010200 VALUES(10,0,'qqqqqaavwsctebqw','sctfxrcwcecbyarb','影视','影视','vedio','',NOW,NOW)
INSERT INTO C2010200 VALUES(11,0,'qqqqqaavwsctcrzt','sctfxrcwcecbyarb','娱乐','娱乐','','',NOW,NOW)
INSERT INTO C2010200 VALUES(12,0,'qqqqqaavwscvsdcs','sctfxrcwcecbyarb','购物','购物','','',NOW,NOW)
INSERT INTO C2010200 VALUES(13,0,'qqqqqaatsgttxwsr','sctfxrcwcecbyarb','开发','开发','','',NOW,NOW)
INSERT INTO C2010200 VALUES(14,0,'qqqqqaagbftdvbys','sctfxrcwcecbyarb','学习','学习','','',NOW,NOW)
INSERT INTO C2010200 VALUES(15,0,'qqqqqazyztadabqd','sctfxrcwcecbyarb','微博','微博','mlog','',NOW,NOW)
INSERT INTO C2010200 VALUES(16,0,'qqqqqaagdwwwgfay','sctfxrcwcecbyarb','收藏','收藏','','',NOW,NOW)
INSERT INTO C2010200 VALUES(17,0,'qqqqqaabwwawrctc','sctfxrcwcecbyarb','租房','租房','','',NOW,NOW)
INSERT INTO C2010200 VALUES(18,0,'qqqqqazqxwgteqgf','sctfxrcwcecbyarb','餐饮','餐饮','','',NOW,NOW)
INSERT INTO C2010200 VALUES(19,0,'qqqqqazqbbdgdbqr','sctfxrcwcecbyarb','创业','创业','','',NOW,NOW)
INSERT INTO C2010200 VALUES(20,0,'qqqqqazsvasfszew','sctfxrcwcecbyarb','记事','记事','','',NOW,NOW)
INSERT INTO C2010200 VALUES(21,0,'qqqqqazearaxvsax','sctfxrcwcecbyarb','办公','办公','','',NOW,NOW)
INSERT INTO C2010200 VALUES(22,0,'qqqqqaavwsdsrgtz','sctfxrcwcecbyarb','其它','其它','','',NOW,NOW)

INSERT INTO C2010200 VALUES(2,0,'qqqqqazeyvfygcqd','sctfxrczgcywxezs','网址收藏','网址收藏','link','',NOW,NOW)

INSERT INTO C2010200 VALUES(3,1,'sctfxrcwrbwrzcyq','sctfxrczgcywxezs','游戏娱乐','游戏娱乐','game','',NOW,NOW)
INSERT INTO C2010200 VALUES(1,0,'qqqqqazddcwbgefx','sctfxrcwrbwrzcyq','单机游戏','单机游戏','','',NOW,NOW)
INSERT INTO C2010200 VALUES(2,0,'qqqqqazddcwbyrqz','sctfxrcwrbwrzcyq','联机游戏','联机游戏','','',NOW,NOW)
INSERT INTO C2010200 VALUES(3,0,'qqqqqazddcwyawsa','sctfxrcwrbwrzcyq','网络游戏','网络游戏','','',NOW,NOW)
INSERT INTO C2010200 VALUES(4,0,'qqqqqazddcwyzgxa','sctfxrcwrbwrzcyq','网页游戏','网页游戏','','',NOW,NOW)
INSERT INTO C2010200 VALUES(5,0,'qqqqqazddcwyxwre','sctfxrcwrbwrzcyq','网络视频','网络视频','','',NOW,NOW)

INSERT INTO C2010200 VALUES(4,1,'sctfxrcwrqygwvxb','sctfxrczgcywxezs','即时通讯','即时通讯','im','',NOW,NOW)
INSERT INTO C2010200 VALUES(1,0,'qqqqqazvcdryecbw','sctfxrcwrqygwvxb','51','51','im:51','',NOW,NOW)
INSERT INTO C2010200 VALUES(2,0,'qqqqqazxrybbbtrw','sctfxrcwrqygwvxb','eBuddy','eBuddy','im:ebuddy','',NOW,NOW)
INSERT INTO C2010200 VALUES(3,0,'qqqqqazebgyffdbv','sctfxrcwrqygwvxb','Fetion','Fetion','im:fetion','',NOW,NOW)
INSERT INTO C2010200 VALUES(4,0,'qqqqqaarsaqferfb','sctfxrcwrqygwvxb','Google Talk','Google Talk','im:gtalk','',NOW,NOW)
INSERT INTO C2010200 VALUES(5,0,'qqqqqazvcdrybycc','sctfxrcwrqygwvxb','KC','KC','im:kc','',NOW,NOW)
INSERT INTO C2010200 VALUES(6,0,'qqqqqaarsaqffqxb','sctfxrcwrqygwvxb','ICQ','ICQ','im:icq','',NOW,NOW)
INSERT INTO C2010200 VALUES(7,0,'qqqqqazsvasvtaqv','sctfxrcwrqygwvxb','jabber','jabber','im:jabber','',NOW,NOW)
INSERT INTO C2010200 VALUES(8,0,'qqqqqaarsawbxxsb','sctfxrcwrqygwvxb','Lava-Lava','Lava-Lava','im:lava','',NOW,NOW)
INSERT INTO C2010200 VALUES(9,0,'qqqqqazxrgtewewq','sctfxrcwrqygwvxb','meebo','meebo','im:meebo','',NOW,NOW)
INSERT INTO C2010200 VALUES(10,0,'qqqqqaarsawbzesy','sctfxrcwrqygwvxb','QQ','QQ','im:qq','',NOW,NOW)
INSERT INTO C2010200 VALUES(11,0,'qqqqqaatsgsswrdv','sctfxrcwrqygwvxb','Skype','Skype','im:skype','',NOW,NOW)
INSERT INTO C2010200 VALUES(12,0,'qqqqqaarsawbwgzw','sctfxrcwrqygwvxb','UC','UC','im:uc','',NOW,NOW)
INSERT INTO C2010200 VALUES(13,0,'qqqqqaabdvredvsv','sctfxrcwrqygwvxb','Web IM','Web IM','','',NOW,NOW)
INSERT INTO C2010200 VALUES(14,0,'qqqqqaarsawgfbwa','sctfxrcwrqygwvxb','Windows Live Messenger','Windows Live Messenger','im:wlm','',NOW,NOW)
INSERT INTO C2010200 VALUES(15,0,'qqqqqaarsawbqczc','sctfxrcwrqygwvxb','Yahoo! Messenger','Yahoo! Messenger','im:yahoo','',NOW,NOW)
INSERT INTO C2010200 VALUES(16,0,'qqqqqaarsawbdydv','sctfxrcwrqygwvxb','网易POPO','网易POPO','im:popo','',NOW,NOW)

INSERT INTO C2010200 VALUES(5,1,'sctfxrcwcvzybzxc','sctfxrczgcywxezs','电子邮件','电子邮件','mail','',NOW,NOW)
INSERT INTO C2010200 VALUES(1,0,'qqqqqazeswxrcztw','sctfxrcwcvzybzxc','126','126','','',NOW,NOW)
INSERT INTO C2010200 VALUES(2,0,'qqqqqaagqzsgzbvy','sctfxrcwcvzybzxc','139','139','','',NOW,NOW)
INSERT INTO C2010200 VALUES(3,0,'qqqqqaarsawbbcrx','sctfxrcwcvzybzxc','163','163','','',NOW,NOW)
INSERT INTO C2010200 VALUES(4,0,'qqqqqazdqcqfdsyy','sctfxrcwcvzybzxc','188','188','','',NOW,NOW)
INSERT INTO C2010200 VALUES(5,0,'qqqqqaaytgscbqfy','sctfxrcwcvzybzxc','AOL','AOL','','',NOW,NOW)
INSERT INTO C2010200 VALUES(6,0,'qqqqqazvcdfqfyzy','sctfxrcwcvzybzxc','Baidu','Baidu','','',NOW,NOW)
INSERT INTO C2010200 VALUES(7,0,'qqqqqazvcdfaqzfb','sctfxrcwcvzybzxc','Email','Email','','',NOW,NOW)
INSERT INTO C2010200 VALUES(8,0,'qqqqqazddcxqqycx','sctfxrcwcvzybzxc','eYou','eYou','','',NOW,NOW)
INSERT INTO C2010200 VALUES(9,0,'qqqqqaarsawbgeyz','sctfxrcwcvzybzxc','Gmail','Gmail','','',NOW,NOW)
INSERT INTO C2010200 VALUES(10,0,'qqqqqaarsawbtwye','sctfxrcwcvzybzxc','Live','Live','','',NOW,NOW)
INSERT INTO C2010200 VALUES(11,0,'qqqqqazqaeabdede','sctfxrcwcvzybzxc','Sohu','Sohu','','',NOW,NOW)
INSERT INTO C2010200 VALUES(12,0,'qqqqqaarsawyqsxv','sctfxrcwcvzybzxc','Sina','Sina','','',NOW,NOW)
INSERT INTO C2010200 VALUES(13,0,'qqqqqaatsgsdxtac','sctfxrcwcvzybzxc','Tom','Tom','','',NOW,NOW)
INSERT INTO C2010200 VALUES(14,0,'qqqqqaagdwexyzts','sctfxrcwcvzybzxc','Yahoo','Yahoo','','',NOW,NOW)
INSERT INTO C2010200 VALUES(15,0,'qqqqqazessaefwaz','sctfxrcwcvzybzxc','Yeah','Yeah','','',NOW,NOW)

INSERT INTO C2010200 VALUES(6,0,'qqqqqaarwwqzddvz','sctfxrczgcywxezs','软件注册','软件注册','soft','',NOW,NOW)
INSERT INTO C2010200 VALUES(1,0,'qqqqqazddcxgesfv','qqqqqaarwwqzddvz','操作系统','操作系统','','',NOW,NOW)
INSERT INTO C2010200 VALUES(2,0,'qqqqqazddcxgdfex','qqqqqaarwwqzddvz','办公软件','办公软件','','',NOW,NOW)
INSERT INTO C2010200 VALUES(3,0,'qqqqqazddcxgrgwy','qqqqqaarwwqzddvz','文字输入','文字输入','','',NOW,NOW)
INSERT INTO C2010200 VALUES(4,0,'qqqqqazddcxgvfcv','qqqqqaarwwqzddvz','上传下载','上传下载','','',NOW,NOW)
INSERT INTO C2010200 VALUES(5,0,'qqqqqazddcxggrrt','qqqqqaarwwqzddvz','即时通讯','即时通讯','','',NOW,NOW)
INSERT INTO C2010200 VALUES(6,0,'qqqqqazddcxgyzqe','qqqqqaarwwqzddvz','桌面管理','桌面管理','','',NOW,NOW)
INSERT INTO C2010200 VALUES(7,0,'qqqqqazddcxbqtba','qqqqqaarwwqzddvz','系统安全','系统安全','','',NOW,NOW)

INSERT INTO C2010200 VALUES(7,0,'qqqqqaarsawtrver','sctfxrczgcywxezs','银行账号','银行账号','bank','',NOW,NOW)
INSERT INTO C2010200 VALUES(1,0,'qqqqqaavwrevdbyr','qqqqqaarsawtrver','网上银行','网上银行','','',NOW,NOW)
INSERT INTO C2010200 VALUES(2,0,'qqqqqaarsawgseyv','qqqqqaarsawtrver','工商银行','工商银行','','',NOW,NOW)
INSERT INTO C2010200 VALUES(3,0,'qqqqqaarsawttysf','qqqqqaarsawtrver','建设银行','建设银行','','',NOW,NOW)
INSERT INTO C2010200 VALUES(4,0,'qqqqqaarsawgzsdy','qqqqqaarsawtrver','交通银行','交通银行','','',NOW,NOW)
INSERT INTO C2010200 VALUES(5,0,'qqqqqaarsawgqcst','qqqqqaarsawtrver','邮政储蓄','邮政储蓄','','',NOW,NOW)
INSERT INTO C2010200 VALUES(6,0,'qqqqqaarsawtbrye','qqqqqaarsawtrver','招商银行','招商银行','','',NOW,NOW)
INSERT INTO C2010200 VALUES(7,0,'qqqqqaarsawtvwwd','qqqqqaarsawtrver','中国银行','中国银行','','',NOW,NOW)

INSERT INTO C2010200 VALUES(8,0,'qqqqqaarsdbrzsby','sctfxrczgcywxezs','通讯名录','通讯名录','','',NOW,NOW)
INSERT INTO C2010200 VALUES(1,0,'qqqqqaarsdbrxzxc','qqqqqaarsdbrzsby','商务同事','商务同事','','',NOW,NOW)
INSERT INTO C2010200 VALUES(2,0,'qqqqqaarsdbfadcg','qqqqqaarsdbrzsby','亲朋好友','亲朋好友','','',NOW,NOW)
INSERT INTO C2010200 VALUES(3,0,'qqqqqaarsdbrdecf','qqqqqaarsdbrzsby','大学同学','大学同学','','',NOW,NOW)
INSERT INTO C2010200 VALUES(4,0,'qqqqqaarsdbrtayv','qqqqqaarsdbrzsby','中学同学','中学同学','','',NOW,NOW)
INSERT INTO C2010200 VALUES(5,0,'qqqqqaavwsdaxdyg','qqqqqaarsdbrzsby','小学同学','小学同学','','',NOW,NOW)
INSERT INTO C2010200 VALUES(6,0,'qqqqqazgxzwvezxv','qqqqqaarsdbrzsby','公共服务','公共服务','','',NOW,NOW)
INSERT INTO C2010200 VALUES(7,0,'qqqqqaarsdbfsfcs','qqqqqaarsdbrzsby','其它','其它','','',NOW,NOW)

INSERT INTO C2010200 VALUES(9,0,'qqqqqaavaqddvafs','sctfxrczgcywxezs','记事便签','记事便签','note','',NOW,NOW)

INSERT INTO C2010200 VALUES(10,0,'qqqqqaavvqqafqaq','sctfxrczgcywxezs','公司账号','公司账号','','',NOW,NOW)

INSERT INTO C2010200 VALUES(11,0,'qqqqqazdvzctvwfs','sctfxrczgcywxezs','文件加密','文件加密','file','',NOW,NOW)
INSERT INTO C2010200 VALUES(1,0,'qqqqqazdvzctyszc','qqqqqazdvzctvwfs','文本文件','文本文件','','',NOW,NOW)
INSERT INTO C2010200 VALUES(2,0,'qqqqqazdvzcgqfbt','qqqqqazdvzctvwfs','图像文件','图像文件','','',NOW,NOW)
INSERT INTO C2010200 VALUES(3,0,'qqqqqazdvzcgxavr','qqqqqazdvzctvwfs','媒体文件','媒体文件','','',NOW,NOW)
INSERT INTO C2010200 VALUES(4,0,'qqqqqazdvzcgdzea','qqqqqazdvzctvwfs','其它文件','其它文件','','',NOW,NOW)

INSERT INTO C2010200 VALUES(12,0,'qqqqqazttgeszezt','sctfxrczgcywxezs','单位转换','单位转换','unit','',NOW,NOW)

INSERT INTO C2010200 VALUES(13,0,'qqqqqazvdcdrqygy','sctfxrczgcywxezs','计划任务','计划任务','task','',NOW,NOW)
INSERT INTO C2010200 VALUES(1,0,'qqqqqazvdcdfvqdq','qqqqqazvdcdrqygy','30分钟内','30分钟以内的计划任务','task:30minute','',NOW,NOW)
INSERT INTO C2010200 VALUES(2,0,'qqqqqazvdcdtargs','qqqqqazvdcdrqygy','1小时内','1小时以内的计划任务','task:1hour','',NOW,NOW)
INSERT INTO C2010200 VALUES(3,0,'qqqqqazvdcdtesfc','qqqqqazvdcdrqygy','2小时内','2小时以内的计划任务','task:2hour','',NOW,NOW)
INSERT INTO C2010200 VALUES(4,0,'qqqqqazvdcdttyte','qqqqqazvdcdrqygy','1天内','1天以内的计划任务','task:1day','',NOW,NOW)
INSERT INTO C2010200 VALUES(5,0,'qqqqqazvdcdgxdae','qqqqqazvdcdrqygy','2天内','2天以内的计划任务','task:2day','',NOW,NOW)
INSERT INTO C2010200 VALUES(6,0,'qqqqqazvdcdgfzre','qqqqqazvdcdrqygy','1周内','1周以内的计划任务','task:1week','',NOW,NOW)
INSERT INTO C2010200 VALUES(7,0,'qqqqqazvdcdgyrfy','qqqqqazvdcdrqygy','1月内','1月以内的计划任务','task:1month','',NOW,NOW)
INSERT INTO C2010200 VALUES(8,0,'qqqqqazvdcdbsfqz','qqqqqazvdcdrqygy','1年内','1年以内的计划任务','task:1year','',NOW,NOW)

INSERT INTO C2010200 VALUES(14,1,'sctfxrcwvqwdeczc','sctfxrczgcywxezs','其它账号','其它账号','','',NOW,NOW)

INSERT INTO P30F0000 VALUES('versions','4','2010-03-21 12:34:56.789')

INSERT INTO P30F1100 VALUES(0,0,'qqqqqaacbrrtysww','0','普通账号','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,1,'qqqqqaacbrrtyssx','qqqqqaacbrrtysww','<登录用户>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,2,'qqqqqaacbrrtysse','qqqqqaacbrrtysww','<登录密码>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(2,6,'qqqqqaaratyqwaev','qqqqqaacbrrtysww','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(1,0,'qqqqqaaratyvddxc','0','网络账号','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,3,'qqqqqaaratybzqaz','qqqqqaaratyvddxc','<网络地址>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,1,'qqqqqaaratybeegy','qqqqqaaratyvddxc','<登录用户>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(2,2,'qqqqqaaratybrffa','qqqqqaaratyvddxc','<登录密码>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(3,4,'qqqqqazxvdcrwqgw','qqqqqaaratyvddxc','<电子邮件>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(4,1,'qqqqqaaratybgsbv','qqqqqaaratyvddxc','<安全问题1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(5,1,'qqqqqaaratybyadv','qqqqqaaratyvddxc','<安全答案1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(6,1,'qqqqqaaratyyaeve','qqqqqaaratyvddxc','<安全问题2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(7,1,'qqqqqaaratyywbra','qqqqqaaratyvddxc','<安全答案2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(8,1,'qqqqqaaratyyxvsa','qqqqqaaratyvddxc','<安全问题3>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(9,1,'qqqqqaaratyydcft','qqqqqaaratyvddxc','<安全答案3>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(10,6,'qqqqqaaratyyrwzf','qqqqqaaratyvddxc','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(2,0,'qqqqqaacbrrtyswe','0','游戏娱乐','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,3,'qqqqqazqqqyvawzd','qqqqqaacbrrtyswe','<官方网站>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,3,'qqqqqazqqqyfrrga','qqqqqaacbrrtyswe','<登录地址>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(2,1,'qqqqqazqqqyrrcaq','qqqqqaacbrrtyswe','<登录用户>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(3,2,'qqqqqazqqqyrtaez','qqqqqaacbrrtyswe','<登录密码>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(4,3,'qqqqqazqqqyvsfzx','qqqqqaacbrrtyswe','<游戏论坛>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(5,1,'qqqqqazqqqytvrad','qqqqqaacbrrtyswe','<安全问题1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(6,1,'qqqqqazqqqytbdyd','qqqqqaacbrrtyswe','<安全答案1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(7,1,'qqqqqazqqqygqwaq','qqqqqaacbrrtyswe','<安全问题2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(8,1,'qqqqqazqqqygagvt','qqqqqaacbrrtyswe','<安全答案2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(9,1,'qqqqqazqqqygwwzr','qqqqqaacbrrtyswe','<安全问题3>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(10,1,'qqqqqazqqqygscwd','qqqqqaacbrrtyswe','<安全答案3>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(11,3,'qqqqqazqqqyybvws','qqqqqaacbrrtyswe','<在线客服>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(12,4,'qqqqqazqqqyfwdrt','qqqqqaacbrrtyswe','<客服邮件>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(13,1,'qqqqqazqqqyfavzv','qqqqqaacbrrtyswe','<客服电话>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(14,1,'qqqqqazqqqyfxwty','qqqqqaacbrrtyswe','<客服传真>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(15,6,'qqqqqazqqqybqfxb','qqqqqaacbrrtyswe','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(3,0,'qqqqqaacbrrtyswx','0','电子邮件','mail','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,3,'qqqqqaacbrrtyswf','qqqqqaacbrrtyswx','<登录地址>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,4,'qqqqqaacbrrtyswv','qqqqqaacbrrtyswx','<邮件地址>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(2,1,'qqqqqaacbrrtyswr','qqqqqaacbrrtyswx','<登录用户>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(3,2,'qqqqqaacbrrtyswt','qqqqqaacbrrtyswx','<邮箱密码>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(4,4,'qqqqqazqqqysdxgv','qqqqqaacbrrtyswx','<保密邮箱>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(5,1,'qqqqqaacbrrtyswy','qqqqqaacbrrtyswx','<安全问题1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(6,1,'qqqqqaacbrrtyssq','qqqqqaacbrrtyswx','<安全答案1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(7,1,'qqqqqaacbrrtyssa','qqqqqaacbrrtyswx','<安全问题2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(8,1,'qqqqqaacbrrtyssz','qqqqqaacbrrtyswx','<安全答案2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(9,1,'qqqqqaacbrrtyssw','qqqqqaacbrrtyswx','<安全问题3>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(10,1,'qqqqqaacbrrtysss','qqqqqaacbrrtyswx','<安全答案3>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(11,6,'qqqqqaaratydfsar','qqqqqaacbrrtyswx','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(4,0,'qqqqqaacbrrtysws','0','即时通讯','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,3,'qqqqqazxryyzcyrf','qqqqqaacbrrtysws','<网站首页>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,1,'qqqqqazxryyzwyqr','qqqqqaacbrrtysws','<登录用户>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(2,2,'qqqqqazqqaqxvcey','qqqqqaacbrrtysws','<登录密码>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(3,3,'qqqqqazqqaqxsqvb','qqqqqaacbrrtysws','<软件首页>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(4,3,'qqqqqazqqaqcbebw','qqqqqaacbrrtysws','<在线登录>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(5,4,'qqqqqazxryyzvesg','qqqqqaacbrrtysws','<电子邮件>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(6,1,'qqqqqazqqaqxbzqq','qqqqqaacbrrtysws','<安全问题1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(7,1,'qqqqqazqqaqxydab','qqqqqaacbrrtysws','<安全答案1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(8,1,'qqqqqazqqaqeqtrf','qqqqqaacbrrtysws','<安全问题2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(9,1,'qqqqqazqqaqeabct','qqqqqaacbrrtysws','<安全答案2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(10,1,'qqqqqazqqaqewxyt','qqqqqaacbrrtysws','<安全问题3>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(11,1,'qqqqqazqqaqesfzy','qqqqqaacbrrtysws','<安全答案3>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(12,6,'qqqqqazqqaqczczd','qqqqqaacbrrtysws','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(5,0,'qqqqqaacbrrtyswd','0','软件注册','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,1,'qqqqqaacbrrtyssg','qqqqqaacbrrtyswd','<软件名称>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,1,'qqqqqaacbrrtyssb','qqqqqaacbrrtyswd','<软件版本>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(2,1,'qqqqqaacbrrtysxq','qqqqqaacbrrtyswd','<注册用户>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(3,1,'qqqqqaacbrrtysxa','qqqqqaacbrrtyswd','<注册号码>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(4,3,'qqqqqaacbrrtyssy','qqqqqaacbrrtyswd','<软件首页>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(5,5,'qqqqqaacbrrtysxz','qqqqqaacbrrtyswd','<注册日期>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(6,5,'qqqqqaacbrrtysxw','qqqqqaacbrrtyswd','<到期日期>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(7,6,'qqqqqaavwssegqvr','qqqqqaacbrrtyswd','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(6,0,'qqqqqaacbrrtyswc','0','银行账号','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,1,'qqqqqaacbrrtyssd','qqqqqaacbrrtyswc','<开户银行>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,1,'qqqqqaacbrrtyssc','qqqqqaacbrrtyswc','<银行账户>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(2,2,'qqqqqaacbrrtyssr','qqqqqaacbrrtyswc','<账户密码>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(3,1,'qqqqqaavaqdyyscz','qqqqqaacbrrtyswc','<开户姓名>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(4,1,'qqqqqaacbrrtyssf','qqqqqaacbrrtyswc','<网上银行>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(5,1,'qqqqqaaratywrrft','qqqqqaacbrrtyswc','<网银账户>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(6,2,'qqqqqaacbrrtyssv','qqqqqaacbrrtyswc','<查询密码>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(7,2,'qqqqqaacbrrtysst','qqqqqaacbrrtyswc','<支付密码>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(8,6,'qqqqqaaratyxcfry','qqqqqaacbrrtyswc','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(7,0,'qqqqqaavaqdfscdv','0','通讯名录','card','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,1,'qqqqqaavaqdfdvdz','qqqqqaavaqdfscdv','<名>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,1,'qqqqqaavaqdffzew','qqqqqaavaqdfscdv','<姓>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(2,1,'qqqqqazrdzfcwvxg','qqqqqaavaqdfscdv','<昵称>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(3,5,'qqqqqaavaqdgrssv','qqqqqaavaqdfscdv','<生日>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(8,1,'qqqqqaavaqdtvxex','qqqqqaavaqdfscdv','<MSN>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(9,1,'qqqqqaavaqdttgxz','qqqqqaavaqdfscdv','<Q Q>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(10,1,'qqqqqaavaqdtfsxg','qqqqqaavaqdfscdv','<ICQ>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(11,1,'qqqqqaavaqdvrecd','qqqqqaavaqdfscdv','<手机>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(12,3,'qqqqqaavaqdtcvce','qqqqqaavaqdfscdv','<个人主页>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(13,1,'qqqqqaavaqdtqtss','qqqqqaavaqdfscdv','<家庭电话>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(14,4,'qqqqqaavaqdtwtyc','qqqqqaavaqdfscdv','<电子邮件>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(15,1,'qqqqqaavaqdgzvcy','qqqqqaavaqdfscdv','<通讯地址>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(16,1,'qqqqqaavaqdgewsc','qqqqqaavaqdfscdv','<邮政编码>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(17,1,'qqqqqaavaqdgtzeq','qqqqqaavaqdfscdv','<公司>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(19,1,'qqqqqaavaqdgbaty','qqqqqaavaqdfscdv','<职位>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(20,1,'qqqqqazrdzvevvyw','qqqqqaavaqdfscdv','<职责>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(21,3,'qqqqqaavaqdbsxev','qqqqqaavaqdfscdv','<公司网站>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(22,1,'qqqqqaavaqdgyrxb','qqqqqaavaqdfscdv','<商务电话>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(23,1,'qqqqqaavaqdbqbeg','qqqqqaavaqdfscdv','<商务传真>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(24,4,'qqqqqaavaqdbzcbf','qqqqqaavaqdfscdv','<工作邮件>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(25,1,'qqqqqaavaqdbewsw','qqqqqaavaqdfscdv','<工作地址>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(26,6,'qqqqqaavzyctcyzr','qqqqqaavaqdfscdv','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(8,0,'qqqqqaavaqdyfbzw','0','记事便签','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,6,'qqqqqaavwsxaxzev','qqqqqaavaqdyfbzw','<记事标题>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(9,0,'qqqqqazdqdfztrgq','0','FTP 账号','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,1,'qqqqqazdqdfevadz','qqqqqazdqdfztrgq','<登录用户>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,2,'qqqqqazdqdfxgxcr','qqqqqazdqdfztrgq','<登录口令>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(3,1,'qqqqqazdqdfsqcvc','qqqqqazdqdfztrgq','<主机地址>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(4,1,'qqqqqazdqdfswcqe','qqqqqazdqdfztrgq','<主机端口>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(5,1,'qqqqqazdqdfdydxy','qqqqqazdqdfztrgq','<远程目录>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(6,1,'qqqqqazdqdfdcved','qqqqqazdqdfztrgq','<登录协议>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(7,1,'qqqqqazdqdfxzxss','qqqqqazdqdfztrgq','<主机类型>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(8,1,'qqqqqazdqdfxraqb','qqqqqazdqdfztrgq','<登录类型>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(9,6,'qqqqqazcfwqxzdvd','qqqqqazdqdfztrgq','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(10,0,'qqqqqazdvqbargat','0','文件加密','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,7,'qqqqqazdvqbzebzd','qqqqqazdvqbargat','<来源文件>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,6,'qqqqqazdvqbzftcc','qqqqqazdvqbargat','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(11,0,'qqqqqazttgrvcztr','0','数值类型','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,8,'qqqqqazttgrvvttc','qqqqqazttgrvcztr','<数值>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,6,'qqqqqazttgrvyfeq','qqqqqazttgrvcztr','<备注信息>','','',NOW,NOW)

INSERT INTO P30F1100 VALUES(12,0,'qqqqqaztdyxwztgx','0','Address Book','card','',NOW,NOW)
INSERT INTO P30F1100 VALUES(0,1,'qqqqqaztdyxwetyd','qqqqqaztdyxwztgx','<First Name>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(1,1,'qqqqqaztdyxwfvdc','qqqqqaztdyxwztgx','<Middle Name>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(2,1,'qqqqqaztdyxwgwyv','qqqqqaztdyxwztgx','<Last Name>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(3,1,'qqqqqaztdyxsazxt','qqqqqaztdyxwztgx','<Phone1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(4,1,'qqqqqaztdyxszvrx','qqqqqaztdyxwztgx','<Phone2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(5,1,'qqqqqaztdyxswbbs','qqqqqaztdyxwztgx','<Fax>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(6,1,'qqqqqaztdyxsxcvr','qqqqqaztdyxwztgx','<Mobile1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(7,1,'qqqqqaztdyxseyww','qqqqqaztdyxwztgx','<Mobile2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(8,3,'qqqqqaztdyxsrzye','qqqqqaztdyxwztgx','<Web>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(9,4,'qqqqqaztdyxsvvtd','qqqqqaztdyxwztgx','<E-mail1>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(10,4,'qqqqqaztdyxsgxwg','qqqqqaztdyxwztgx','<E-mail2>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(11,1,'qqqqqaztdyxxzayq','qqqqqaztdyxwztgx','<Country>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(12,1,'qqqqqaztdyxxwsse','qqqqqaztdyxwztgx','<City>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(13,1,'qqqqqaztdyxxsfax','qqqqqaztdyxwztgx','<Address>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(14,1,'qqqqqaztdyxxewdg','qqqqqaztdyxwztgx','<Company Name>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(15,1,'qqqqqaztdyxxcdwy','qqqqqaztdyxwztgx','<Account Number>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(16,1,'qqqqqaztdyxxfvbv','qqqqqaztdyxwztgx','<Tax Number>','','',NOW,NOW)
INSERT INTO P30F1100 VALUES(17,1,'qqqqqaztdyxxtcwq','qqqqqaztdyxwztgx','<Register Number>','','',NOW,NOW)

INSERT INTO P30F0800 VALUES(0,1,'qqqqqazysztvbqqq','cot(x)','1/tan(x)','余切函数','角θ的邻边比对边')
INSERT INTO P30F0800 VALUES(1,1,'qqqqqazyszttecxv','sec(x)','1/cos(x)','正割函数','角θ的斜边比邻边')
INSERT INTO P30F0800 VALUES(2,1,'qqqqqazyszyaccqe','csc(x)','1/sin(x)','余割函数','角θ的斜边比对边')